if(DEFINED ENV{ECM_DIR})
    set(ECM_DIR {ECM_DIR})
elseif(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/cmake/ecm/ECMConfig.cmake")
    set(ECM_DIR "${CMAKE_CURRENT_SOURCE_DIR}/cmake/ecm")
elseif(CMAKE_HOST_WIN32)
    set(ECM_DIR "C:/msys64/ucrt64/share/ECM/cmake")
else()
    set(ECM_DIR /usr/share/ECM/cmake)
endif()
find_package(ECM REQUIRED CONFIG)
