# Generated by BoostInstall.cmake for boost_dll-1.90.0

if(Boost_VERBOSE OR Boost_DEBUG)
  message(STATUS "Found boost_dll ${boost_dll_VERSION} at ${boost_dll_DIR}")
endif()

include(CMakeFindDependencyMacro)

if(NOT boost_dll_boost_fs_FOUND)
  find_dependency(boost_dll_boost_fs 1.90.0 EXACT HINTS "${CMAKE_CURRENT_LIST_DIR}/..")
endif()

include("${CMAKE_CURRENT_LIST_DIR}/boost_dll-targets.cmake")
